// Auto-generated by createHeaderFile.py
class Test_0 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 255, 255);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = {
			19920, 21720, 23520, 34320, 36120, 37920, 39720, 41520, 43320, 45120, 46920, 48720, 
			50520, 52320, 54120, 55920, 56820, 57720, 58620, 59520, 60420, 61320, 62220, 63120, 
			64020, 64920, 65820, 66720, 68520, 70320, 72120, 73920, 75720, 79320, 82920
		};
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 05:32:00, interval ~1800s
		{ 0, 945 },
		{ 60, 943 },
		{ 120, 941 },
        { 180, 939 },
        { 240, 936 },
        { 300, 934 },
        { 360, 932 },
        { 420, 930 },
        { 480, 928 },
        { 540, 926 },
        { 600, 924 },
        { 660, 922 },
        { 720, 920 },
        { 780, 918 },
        { 840, 914 },
        { 900, 912 },
        { 960, 910 },
        { 1020, 906 },
        { 1080, 904 },
        { 1140, -1 },
	};
};


// === Global List of Routes ===
inline const std::vector<const TrainRoute*> getAllRoutes() {
	static const std::vector<const TrainRoute*> routes = {
		new Test_0()
	};
	return routes;
}