// Auto-generated by createHeaderFile.py
class JVL__0_Schedule_0 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(0, 191, 191);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = {
			19920, 21720, 23520, 34320, 36120, 37920, 39720, 41520, 43320, 45120, 46920, 48720, 
			50520, 52320, 54120, 55920, 56820, 57720, 58620, 59520, 60420, 61320, 62220, 63120, 
			64020, 64920, 65820, 66720, 68520, 70320, 72120, 73920, 75720, 79320, 82920
		};
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 05:32:00, interval ~1800s
		{ -171, 100 },
		//{ -283, 101 },
		//{ -247, 102 },
		{ 83, 105 },
		{ 192, 108 },
		{ 203, 183 },
		{ 324, 184 },
		{ 383, 185 },
		{ 611, 186 },
		{ 795, 187 },
		{ 874, 188 },
		{ 981, 189 },
		{ 1087, 190 },
		{ 1277, 191 },
		{ 1426, 192 },
		{ 1726, -1 }
	};
};

class JVL__1_Schedule_0 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(0, 191, 191);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = {
			21600, 23400, 24300, 25200, 26100, 27000, 27900, 28800, 29700, 30600, 31500, 32400, 
			34200, 36000, 37800, 39600, 41400, 43200, 45000, 46800, 48600, 50400, 52200, 54000, 
			66600, 68400, 70200, 72000, 73800, 75600, 77400, 81000, 84600
		};
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 06:00:00, interval ~1800s
		{ -169, 192 },
		{ 89, 191 },
		{ 245, 190 },
		{ 431, 189 },
		{ 490, 188 },
		{ 609, 187 },
		{ 717, 186 },
		{ 910, 185 },
		{ 1103, 184 },
		{ 1163, 183 },
		{ 1294, 108 },
		{ 1337, 105 },
		//{ 1446, 102 },
		//{ 1401, 101 },
		{ 1429, 100 },
		{ 1729, -1 }
	};
};

class JVL__0_Schedule_1 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(0, 191, 191);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 22320 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 06:12:00
		{ -292, 100 },
		//{ -18, 101 },
		{ 82, 105 },
		{ 199, 108 },
		{ 207, 183 },
		{ 324, 184 },
		{ 477, 185 },
		{ 717, 186 },
		{ 832, 187 },
		{ 952, 188 },
		{ 1062, 189 },
		{ 1164, 190 },
		{ 1523, 191 },
		{ 1674, 192 },
		{ 1974, -1 }
	};
};

class JVL__0_Schedule_2 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(0, 191, 191);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 24120, 25020, 25920, 26820, 27720, 28620, 29520, 30420, 32220 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 06:42:00, interval ~900s
		{ -114, 100 },
		//{ -200, 101 },
		{ 92, 105 },
		{ 157, 108 },
		{ 207, 183 },
		{ 330, 184 },
		{ 497, 185 },
		{ 740, 186 },
		{ 1052, 187 },
		{ 1169, 188 },
		{ 1283, 189 },
		{ 1399, 190 },
		{ 1576, 191 },
		{ 1703, 192 },
		{ 2003, -1 }
	};
};

class JVL__1_Schedule_1 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(0, 191, 191);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 55800, 57600, 58500, 59400, 60300, 61200, 62100, 63000, 63900, 64800, 65700, 67500 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 15:30:00, interval ~1800s
		{ -84, 192 },
		{ 102, 191 },
		{ 257, 190 },
		{ 492, 189 },
		{ 597, 188 },
		{ 695, 187 },
		{ 801, 186 },
		{ 935, 185 },
		{ 1245, 184 },
		{ 1455, 183 },
		{ 1571, 108 },
		{ 1635, 105 },
		//{ 1697, 102 },
		//{ 1702, 101 },
		{ 1696, 100 },
		{ 1996, -1 }
	};
};

class HVL__0_Schedule_0 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 96, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = {
			21000, 22080, 24240, 25680, 26880, 28020, 29220, 30600, 31800, 33000, 34200, 35400, 
			36600, 37800, 39000, 40200, 41400, 42600, 43800, 45000, 46200, 47400, 48600, 49800, 
			51000, 52200, 53400, 54360, 66900, 68700, 70500, 72300, 74100, 75900, 77700, 79500, 
			81300, 83100
		};
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 05:50:00, interval ~1080s
		//{ -223, 100 },
		//{ -288, 101 },
		{ -293, 102 },
		//{ -287, 103 },
		//{ -295, 104 },
		{ 102, 106 },
		//{ 130, 107 },
		{ 195, 109 },
		{ 199, 110 },
		{ 225, 112 },
		{ 254, 114 },
		{ 286, 116 },
		{ 300, 117 },
		{ 360, 118 },
		{ 392, 119 }, // Was: 360
		{ 424, 120 },
		{ 450, 121 },
		{ 497, 122 },
		{ 563, 123 },
		{ 616, 124 },
		{ 720, 125 },
		{ 780, 126 },
		{ 804, 127 },
		{ 856, 128 },
		{ 920, 129 },
		{ 945, 130 },
		{ 980, 131 },
		{ 1041, 132 },
		{ 1133, 133 },
		{ 1173, 134 },
		{ 1233, 135 },
		{ 1289, 136 },
		{ 1360, 137 },
		{ 1413, 138 },
		{ 1455, 139 },
		{ 1507, 140 },
		{ 1563, 141 },
		{ 1634, 142 },
		{ 1684, 143 },
		{ 1754, 144 },
		{ 1817, 145 },
		{ 1884, 146 },
		{ 1929, 147 },
		{ 1998, 148 },
		{ 2094, 149 },
		{ 2123, 150 },
		{ 2217, 151 },
		{ 2284, 152 },
		{ 2346, 153 },
		{ 2401, 154 },
		{ 2479, 155 },
		{ 2584, 156 },
		{ 2624, 157 },
		{ 2673, 158 },
		{ 2722, 159 },
		{ 2776, 160 },
		{ 2836, 161 },
		//{ 2824, 162 },
		//{ 2132, 229 },
		//{ 2182, 230 },
		{ 2896, -1 }
	};
};

class HVL__1_Schedule_0 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 96, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = {
			16200, 19800, 30000, 31200, 32400, 33600, 34800, 36000, 37200, 38400, 39600, 40800, 
			42000, 43200, 44400, 45600, 46800, 48000, 49200, 50400, 51600, 52800, 54000, 55200, 
			56340, 57720, 61440, 62520, 63660, 65220, 66600, 68400, 70200, 72000, 75600, 79200, 
			82800
		};
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 04:30:00, interval ~3600s
		//{ -240, 162 },
		{ 14, 161 },
		{ 110, 160 },
		{ 200, 159 },
		{ 214, 158 },
		{ 250, 157 },
		{ 336, 156 },
		{ 415, 155 },
		{ 454, 154 },
		{ 491, 153 },
		{ 589, 152 },
		{ 650, 151 },
		{ 720, 150 },
		{ 807, 149 },
		{ 827, 148 },
		{ 946, 147 },
		{ 955, 146 },
		{ 1064, 145 },
		{ 1140, 144 },
		{ 1180, 143 },
		{ 1210, 142 },
		{ 1304, 141 },
		{ 1330, 140 },
		{ 1424, 139 },
		{ 1436, 138 },
		{ 1516, 137 },
		{ 1536, 136 },
		{ 1640, 135 },
		{ 1684, 134 },
		{ 1761, 133 },
		{ 1795, 132 },
		{ 1881, 131 },
		{ 1906, 130 },
		{ 1930, 129 },
		{ 2040, 128 },
		{ 2048, 127 }, // Was: 2039
		{ 2057, 126 },
		{ 2150, 125 },
		{ 2166, 124 },
		{ 2282, 123 },
		{ 2333, 122 }, // Was: 2281
		{ 2385, 121 },
		{ 2395, 120 },
		{ 2485, 119 },
		{ 2502, 118 }, // Was: 2484
		{ 2519, 117 },
		{ 2526, 116 },
		{ 2540, 114 },
		{ 2612, 112 },
		{ 2624, 110 },
		{ 2645, 109 },
		//{ 2769, 107 },
		{ 2724, 106 },
		//{ 2836, 104 },
		//{ 2837, 103 },
		{ 2772, 102 },
		//{ 2830, 101 },
		{ 2832, -1 }
	};
};

class HVL__1_Schedule_1 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 96, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 21600, 22800, 24000, 26160, 58860 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 06:00:00, interval ~1200s
		//{ -288, 162 },
		{ -49, 161 },
		{ 103, 160 },
		{ 201, 159 },
		{ 215, 158 },
		{ 291, 157 },
		{ 350, 156 },
		{ 440, 155 },
		{ 462, 154 },
		{ 557, 153 },
		{ 595, 152 },
		{ 682, 151 },
		{ 722, 150 },
		{ 829, 149 },
		{ 853, 148 },
		{ 952, 147 },
		{ 1039, 146 },
		{ 1072, 145 },
		{ 1159, 144 },
		{ 1179, 143 }, // Was: 1131
		{ 1199, 142 },
		{ 1259, 140 },
		{ 1317, 139 },
		{ 1332, 137 },
		{ 1408, 136 },
		{ 1453, 135 },
		{ 1535, 134 },
		{ 1543, 133 },
		{ 1576, 132 },
		{ 1606, 131 },
		{ 1651, 130 },
		{ 1682, 129 },
		{ 1739, 128 },
		{ 1759, 127 }, // Was: 1679
		{ 1780, 126 }, // Was: 1695
		{ 1802, 125 },
		{ 1891, 124 },
		{ 1929, 123 },
		{ 1981, 122 }, // Was: 1929
		{ 2034, 121 },
		{ 2047, 120 },
		{ 2067, 119 }, // Was: 2045
		{ 2088, 118 },
		{ 2101, 117 },
		{ 2279, 116 },
		{ 2299, 114 }, // Was: 2157
		{ 2319, 112 }, // Was: 2259
		{ 2339, 110 }, // Was: 2276
		{ 2349, 109 }, // Was: 2267
		//{ 2360, 107 },
		{ 2367, 106 },
		//{ 2379, 101 },
		{ 2427, -1 }
	};
};

class HVL__1_Schedule_2 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 96, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 22800, 24000, 25200, 26400, 27420, 28800, 30000 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 06:20:00, interval ~1200s
		{ -293, 145 },
		{ 84, 144 },
		{ 198, 143 },
		{ 217, 142 },
		{ 315, 141 },
		{ 346, 140 },
		{ 397, 139 },
		{ 478, 138 },
		{ 529, 137 },
		{ 567, 136 },
		{ 677, 135 },
		{ 727, 134 },
		{ 798, 133 },
		{ 837, 132 },
		{ 914, 131 },
		{ 952, 130 },
		{ 1037, 129 },
		{ 1055, 128 }, // Was: 1009
		{ 1074, 127 },
		{ 1076, 126 },
		{ 1125, 125 },
		{ 1317, 124 },
		{ 1324, 123 }, // Was: 1204
		{ 1332, 122 },
		{ 1401, 121 },
		{ 1407, 120 }, // Was: 1329
		{ 1413, 119 },
		{ 1498, 118 },
		{ 1518, 117 }, // Was: 1494
		{ 1538, 116 }, // Was: 1444
		{ 1570, 114 }, // Was: 1506
		{ 1603, 112 },
		{ 1643, 110 },
		{ 1648, 109 },
		//{ 1776, 107 },
		{ 1682, 106 },
		//{ 1726, 104 },
		//{ 1763, 103 },
		{ 1809, 102 },
		//{ 1814, 101 },
		{ 1869, -1 }
	};
};

class HVL__1_Schedule_3 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 96, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 25200, 27600, 28800 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 07:00:00, interval ~2400s
		//{ -41, 162 },
		{ -153, 161 },
		{ 108, 160 },
		{ 199, 159 },
		{ 219, 158 },
		{ 243, 157 },
		{ 347, 156 },
		{ 430, 155 },
		{ 478, 154 },
		{ 560, 153 },
		{ 643, 152 },
		{ 687, 151 },
		{ 837, 150 },
		{ 880, 149 }, // Was: 837
		{ 923, 148 },
		{ 961, 147 },
		{ 1043, 146 },
		{ 1123, 145 },
		{ 1163, 144 },
		{ 1473, 143 },
		{ 1493, 142 }, // Was: 1210
		{ 1513, 140 }, // Was: 1319
		{ 1533, 139 }, // Was: 1323
		{ 1553, 138 }, // Was: 1324
		{ 1573, 137 }, // Was: 1437
		{ 1593, 136 }, // Was: 1438
		{ 1613, 135 }, // Was: 1519
		{ 1625, 134 }, // Was: 1524
		{ 1638, 133 },
		{ 1663, 132 },
		{ 1667, 131 }, // Was: 1606
		{ 1672, 130 },
		{ 1759, 129 },
		{ 1797, 128 },
		{ 1808, 127 },
		{ 1811, 126 }, // Was: 1803
		{ 1814, 125 },
		{ 1920, 124 },
		{ 2100, 123 },
		{ 2120, 122 }, // Was: 2037
		{ 2130, 121 }, // Was: 2081
		{ 2140, 120 },
		{ 2143, 119 },
		{ 2150, 118 }, // Was: 2044
		{ 2158, 117 },
		{ 2267, 116 },
		{ 2279, 114 },
		{ 2287, 112 },
		{ 2317, 110 },
		{ 2373, 109 },
		//{ 2602, 107 },
		{ 2435, 106 },
		//{ 2470, 103 },
		//{ 2530, 101 },
		{ 2495, -1 }
	};
};

class HVL__0_Schedule_1 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 96, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 55080, 56160, 57420, 58620, 59820, 61020, 61980, 62520, 63780, 65100 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 15:18:00, interval ~1080s
		//{ -290, 101 },
		{ -265, 102 },
		//{ -177, 103 },
		{ 135, 106 },
		//{ 114, 107 },
		{ 176, 109 },
		{ 199, 110 },
		{ 244, 112 },
		{ 265, 114 },
		{ 278, 116 },
		{ 296, 117 },
		{ 356, 118 },
		{ 366, 119 },
		{ 397, 120 },
		{ 420, 121 },
		{ 430, 122 },
		{ 500, 123 },
		{ 554, 124 },
		{ 656, 125 },
		{ 720, 126 },
		{ 726, 127 },
		{ 727, 128 },
		{ 781, 129 },
		{ 791, 130 },
		{ 846, 131 },
		{ 889, 132 },
		{ 976, 133 },
		{ 1001, 134 },
		{ 1021, 135 },
		{ 1096, 136 },
		{ 1150, 137 },
		{ 1161, 138 },
		{ 1186, 139 },
		{ 1261, 140 },
		{ 1290, 141 }, // Was: 1259
		{ 1319, 142 },
		{ 1386, 143 },
		{ 1400, 144 },
		{ 1534, 145 },
		{ 1580, 146 },
		{ 1676, 147 },
		{ 1740, 148 },
		{ 1844, 149 },
		{ 1875, 150 },
		{ 1980, 151 },
		{ 2034, 152 },
		{ 2095, 153 },
		{ 2169, 154 },
		{ 2226, 155 },
		{ 2325, 156 },
		{ 2343, 157 },
		{ 2406, 158 },
		{ 2478, 159 },
		{ 2530, 160 },
		{ 2774, 161 },
		//{ 2550, 162 },
		{ 2834, -1 }
	};
};

class HVL__0_Schedule_2 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 96, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 55740, 56940, 58140, 59340, 60540, 62100, 63300, 64200, 65460 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 15:29:00, interval ~1200s
		//{ -294, 101 },
		{ -255, 102 },
		//{ -75, 103 },
		//{ -295, 104 },
		{ 138, 106 },
		//{ 148, 107 },
		{ 166, 109 },
		{ 258, 110 },
		{ 261, 112 },
		{ 269, 114 },
		{ 287, 116 },
		{ 299, 117 },
		{ 491, 118 },
		{ 511, 119 }, // Was: 418
		{ 531, 120 }, // Was: 431
		{ 551, 121 }, // Was: 419
		{ 571, 122 }, // Was: 481
		{ 593, 123 }, // Was: 529
		{ 616, 124 },
		{ 661, 125 },
		{ 776, 126 },
		{ 816, 127 }, // Was: 775
		{ 856, 128 },
		{ 860, 129 },
		{ 901, 130 },
		{ 976, 131 },
		{ 1016, 132 },
		{ 1106, 133 },
		{ 1145, 134 },
		{ 1219, 135 },
		{ 1269, 136 },
		{ 1340, 137 },
		{ 1425, 138 },
		{ 1456, 139 },
		{ 1500, 140 },
		{ 1580, 141 },
		{ 1602, 142 },
		{ 1700, 143 },
		{ 1719, 144 },
		{ 1779, -1 }
	};
};

class HVL__1_Schedule_4 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 96, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 60120 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 16:42:00
		{ -80, 145 },
		{ 315, 144 },
		{ 393, 143 },
		{ 458, 142 },
		{ 561, 141 },
		{ 581, 140 }, // Was: 497
		{ 651, 139 }, // Was: 517
		{ 721, 138 },
		{ 738, 137 },
		{ 851, 136 },
		{ 858, 135 },
		{ 915, 134 },
		{ 988, 133 },
		{ 1317, 132 },
		{ 1337, 131 }, // Was: 1113
		{ 1357, 130 }, // Was: 1153
		{ 1377, 128 }, // Was: 1195
		{ 1397, 127 }, // Was: 1263
		{ 1417, 126 }, // Was: 1363
		{ 1546, 125 }, // Was: 1275
		{ 1676, 124 },
		{ 1696, 123 }, // Was: 1435
		{ 1716, 122 }, // Was: 1620
		{ 1736, 121 }, // Was: 1598
		{ 1756, 120 }, // Was: 1492
		{ 1776, 119 }, // Was: 1571
		{ 1808, 118 }, // Was: 1740
		{ 1840, 117 },
		{ 1843, 116 }, // Was: 1811
		{ 1845, 114 },
		{ 1881, 112 },
		{ 2046, 110 },
		{ 2118, 109 }, // Was: 1843
		//{ 2191, 107 },
		{ 2138, 106 }, // Was: 1898
		//{ 1968, 103 },
		{ 2106, -1 }
	};
};

class HVL__1_Schedule_5 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 96, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 61260 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 17:01:00
		{ 27, 145 },
		{ 178, 144 },
		{ 337, 143 },
		{ 646, 142 },
		{ 708, 141 }, // Was: 622
		{ 771, 140 },
		{ 773, 138 },
		{ 818, 137 }, // Was: 670
		{ 863, 136 },
		{ 910, 135 },
		{ 985, 134 },
		{ 1216, 133 },
		{ 1236, 132 }, // Was: 1105
		{ 1256, 131 }, // Was: 975
		{ 1308, 130 }, // Was: 1213
		{ 1361, 129 },
		{ 1411, 128 }, // Was: 1125
		{ 1461, 127 },
		{ 1481, 126 }, // Was: 1345
		{ 1552, 125 }, // Was: 1360
		{ 1624, 124 },
		{ 1685, 123 }, // Was: 1372
		{ 1746, 122 },
		{ 1766, 121 }, // Was: 1499
		{ 1811, 120 }, // Was: 1520
		{ 1856, 118 },
		{ 1861, 117 },
		{ 1881, 116 }, // Was: 1818
		{ 1918, 114 }, // Was: 1790
		{ 1955, 112 },
		{ 1975, 110 },
		{ 2057, 109 },
		//{ 2150, 107 },
		{ 2060, 106 },
		//{ 2176, 103 },
		{ 2418, 102 },
		{ 2478, -1 }
	};
};

class KPL__0_Schedule_0 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(159, 223, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = {
			21120, 22800, 24600, 25800, 27060, 28680, 29580, 30780, 31980, 33180, 34380, 35580, 
			36780, 37980, 39180, 40380, 41580, 42780, 43980, 45180, 46380, 47580, 48780, 49980, 
			51180, 52380, 53580, 54780, 65640, 67440, 69240, 71040, 72840, 74640, 76440, 78240, 
			80040, 81840, 83640
		};
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 05:52:00, interval ~1680s
		//{ 695, 100 },
		{ -292, 101 },
		//{ -291, 102 },
		//{ -291, 103 },
		//{ -294, 104 },
		{ 130, 106 },
		//{ 135, 107 },
		{ 173, 108 },
		{ 200, 110 },
		{ 248, 111 },
		{ 264, 113 },
		{ 279, 115 },
		{ 303, 193 },
		{ 424, 194 },
		{ 660, 195 },
		{ 735, 196 },
		{ 770, 197 },
		{ 856, 198 },
		{ 884, 199 },
		{ 927, 200 },
		{ 983, 201 },
		{ 1043, 202 },
		{ 1102, 203 },
		{ 1162, 204 },
		{ 1223, 205 },
		{ 1324, 206 },
		{ 1364, 207 },
		{ 1450, 208 },
		{ 1503, 209 },
		{ 1575, 210 },
		{ 1614, 211 },
		{ 1698, 212 },
		{ 1744, 213 },
		{ 1823, 214 },
		{ 1879, 216 },
		{ 2084, 217 },
		{ 2208, 218 },
		{ 2260, 219 },
		{ 2324, 220 },
		{ 2421, 221 },
		{ 2657, 222 },
		{ 2829, 223 },
		{ 2960, 224 },
		{ 3063, 225 },
		{ 3175, 226 },
		{ 3246, 227 },
		//{ 3405, 228 },
		{ 3360, 229 },
		{ 3395, 230 },
		{ 3534, 231 },
		{ 3598, 232 },
		{ 3658, 233 },
		{ 3724, 234 },
		{ 4024, -1 }
	};
};

class KPL__1_Schedule_0 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(159, 223, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = {
			18000, 19800, 30300, 31500, 32700, 33600, 34800, 36000, 37200, 38400, 39600, 40800, 
			42000, 43200, 44400, 45600, 46800, 48000, 49200, 50400, 51600, 52800, 54120, 55200, 
			56520, 57900, 58800, 60000, 61200, 62400, 63660, 65100, 67260, 68400, 70200, 72000, 
			75600, 79200, 82800
		};
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 05:00:00, interval ~1800s
		{ -285, 234 },
		{ 78, 233 },
		{ 115, 232 },
		{ 238, 231 },
		{ 356, 230 },
		{ 374, 229 },
		//{ 418, 228 },
		{ 442, 227 },
		{ 598, 226 },
		{ 658, 225 },
		{ 722, 224 },
		{ 834, 223 },
		{ 923, 222 },
		{ 1144, 221 },
		{ 1323, 220 },
		{ 1401, 219 },
		{ 1435, 218 },
		{ 1520, 217 },
		{ 1686, 216 },
		//{ 2045, 215 },
		{ 1877, 214 },
		{ 1924, 213 },
		{ 2004, 212 },
		{ 2051, 211 },
		{ 2135, 210 },
		{ 2167, 209 },
		{ 2275, 208 },
		{ 2285, 207 },
		{ 2373, 206 },
		{ 2430, 205 },
		{ 2514, 204 },
		{ 2594, 203 },
		{ 2630, 202 },
		{ 2715, 201 },
		{ 2744, 200 },
		{ 2766, 199 },
		{ 2840, 198 },
		{ 2887, 197 },
		{ 2968, 196 },
		{ 3017, 195 },
		{ 3395, 194 },
		{ 3420, 193 },
		{ 3476, 115 },
		{ 3486, 113 },
		{ 3540, 111 },
		{ 3604, 110 },
		{ 3697, 108 }, // Was: 3595
		//{ 3791, 107 },
		{ 3771, 106 }, // Was: 3675
		//{ 3845, 104 },
		//{ 3795, 103 },
		//{ 3696, 102 },
		{ 3791, 101 }, // Was: 3730
		{ 4030, -1 }
	};
};

class KPL__1_Schedule_1 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(159, 223, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 21600, 23280, 24360, 25080, 26280, 27480, 28680 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 06:00:00, interval ~1680s
		{ -293, 234 },
		{ 81, 233 },
		{ 112, 232 },
		{ 242, 231 },
		{ 359, 230 },
		{ 367, 229 },
		//{ 443, 228 },
		{ 444, 227 },
		{ 600, 226 },
		{ 715, 225 },
		{ 722, 224 },
		{ 842, 223 },
		{ 924, 222 },
		{ 1092, 221 },
		{ 1323, 220 },
		{ 1402, 219 },
		{ 1438, 218 },
		{ 1522, 217 },
		{ 1684, 216 },
		//{ 1924, 215 },
		{ 1882, 214 },
		{ 1907, 213 },
		{ 2003, 212 },
		{ 2037, 211 },
		{ 2124, 210 },
		{ 2162, 209 },
		{ 2265, 208 },
		{ 2283, 207 },
		{ 2392, 206 },
		{ 2475, 205 },
		{ 2522, 204 },
		{ 2523, 203 },
		{ 2532, 201 },
		{ 2757, 200 },
		{ 2777, 199 }, // Was: 2642
		{ 2797, 198 }, // Was: 2643
		{ 2817, 197 }, // Was: 2649
		{ 2837, 196 }, // Was: 2691
		{ 3000, 195 }, // Was: 2753
		{ 3163, 194 },
		{ 3203, 193 }, // Was: 3155
		{ 3244, 115 },
		{ 3289, 113 },
		{ 3317, 111 },
		{ 3323, 110 },
		{ 3345, 108 },
		//{ 3438, 107 },
		{ 3439, 106 },
		//{ 3563, 103 },
		//{ 3558, 102 },
		{ 3813, 101 },
		{ 4113, -1 }
	};
};

class KPL__1_Schedule_2 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(159, 223, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 22380, 24300, 25740, 30960 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 06:13:00, interval ~1920s
		{ -292, 214 },
		{ 85, 213 },
		{ 168, 212 },
		{ 262, 211 },
		{ 304, 210 },
		{ 382, 209 },
		{ 400, 208 },
		{ 519, 207 },
		{ 547, 206 },
		{ 622, 205 },
		{ 719, 204 },
		{ 742, 203 },
		{ 828, 202 },
		{ 864, 201 },
		{ 967, 200 },
		{ 988, 199 },
		{ 1007, 198 },
		{ 1103, 197 },
		{ 1143, 196 },
		{ 1223, 195 },
		{ 1522, 194 },
		{ 1623, 193 },
		{ 1712, 113 },
		{ 1743, 111 },
		{ 1783, 110 }, // Was: 1737
		{ 1823, 108 },
		//{ 2053, 107 },
		{ 1838, 106 },
		//{ 1900, 104 },
		//{ 2152, 103 },
		//{ 2058, 102 },
		{ 1942, 101 },
		{ 2242, -1 }
	};
};

class KPL__0_Schedule_1 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(159, 223, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 25380, 54060, 55260, 56460, 57660, 58860, 63660, 64860 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 07:03:00, interval ~28680s
		//{ 54, 100 },
		{ -294, 101 },
		//{ -66, 102 },
		//{ -293, 103 },
		//{ -294, 104 },
		{ 139, 106 },
		//{ 140, 107 },
		{ 164, 108 },
		{ 188, 110 },
		{ 260, 111 },
		{ 270, 113 },
		{ 272, 115 },
		{ 296, 193 },
		{ 421, 194 },
		{ 663, 195 },
		{ 740, 196 },
		{ 765, 197 },
		{ 860, 198 },
		{ 893, 199 },
		{ 976, 200 },
		{ 997, 201 },
		{ 1099, 202 },
		{ 1124, 203 },
		{ 1219, 204 },
		{ 1257, 205 },
		{ 1557, -1 }
	};
};

class KPL__1_Schedule_3 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(159, 223, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 25860 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 07:11:00
		{ -293, 207 },
		{ 23, 206 },
		{ 42, 205 },
		{ 147, 204 },
		{ 190, 203 },
		{ 270, 202 },
		{ 382, 201 },
		{ 403, 200 },
		{ 448, 199 },
		{ 503, 198 },
		{ 549, 197 },
		{ 624, 196 },
		{ 744, 195 },
		{ 1050, 194 },
		{ 1141, 193 },
		{ 1180, 113 },
		{ 1226, 111 },
		{ 1270, 110 },
		{ 1301, 108 },
		{ 1360, 106 },
		//{ 1400, 103 },
		{ 1660, -1 }
	};
};

class KPL__1_Schedule_4 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(159, 223, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 26940, 27720, 29100, 30300, 55680, 59220, 66480 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 07:29:00, interval ~780s
		{ -196, 206 },
		{ 70, 205 },
		{ 195, 204 },
		{ 257, 203 },
		{ 314, 202 },
		{ 377, 201 },
		{ 440, 200 },
		{ 499, 199 },
		{ 514, 198 },
		{ 610, 197 },
		{ 673, 196 },
		{ 738, 195 },
		{ 1077, 194 },
		{ 1148, 193 },
		{ 1272, 115 },
		{ 1292, 113 }, // Was: 1219
		{ 1296, 111 }, // Was: 1269
		{ 1300, 110 },
		{ 1337, 108 },
		{ 1378, 106 },
		//{ 1462, 103 },
		//{ 1456, 102 },
		{ 1538, 101 },
		{ 1838, -1 }
	};
};

class KPL__1_Schedule_5 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(159, 223, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 27300 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 07:35:00
		{ -292, 214 },
		{ 54, 213 },
		{ 164, 212 },
		{ 260, 211 },
		{ 302, 210 },
		{ 379, 209 },
		{ 384, 208 },
		{ 541, 207 },
		{ 543, 206 },
		{ 742, 205 },
		{ 861, 204 },
		{ 862, 203 },
		{ 979, 202 },
		{ 1004, 201 },
		{ 1104, 200 },
		{ 1128, 199 },
		{ 1152, 198 },
		{ 1245, 197 },
		{ 1341, 196 },
		{ 1364, 195 },
		{ 1750, 194 },
		{ 1849, 193 },
		{ 1860, 115 },
		{ 1862, 113 },
		{ 1939, 111 },
		{ 1962, 110 },
		{ 1973, 108 },
		{ 2063, 106 },
		{ 2191, 101 },
		{ 2491, -1 }
	};
};

class KPL__0_Schedule_2 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(159, 223, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 56100, 57300, 58500, 59700, 60900, 62280, 63300, 64500 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 15:35:00, interval ~1200s
		//{ -287, 102 },
		//{ -293, 103 },
		//{ -290, 104 },
		{ 136, 106 },
		//{ 358, 107 },
		{ 166, 108 },
		{ 257, 110 },
		{ 261, 111 },
		{ 277, 113 },
		{ 289, 115 },
		//{ 1806, 118 },
		//{ 1757, 120 },
		//{ 1687, 121 },
		//{ 1676, 122 },
		//{ 1556, 124 },
		//{ 1436, 126 },
		//{ 1416, 127 },
		//{ 1326, 129 },
		//{ 1287, 130 },
		//{ 1276, 131 },
		//{ 1206, 132 },
		//{ 1156, 133 },
		//{ 1076, 134 },
		//{ 1037, 135 },
		//{ 966, 136 },
		//{ 917, 137 },
		//{ 836, 139 },
		//{ 796, 140 },
		//{ 726, 141 },
		//{ 676, 142 },
		//{ 556, 144 },
		//{ 477, 145 },
		//{ 436, 146 },
		//{ 366, 147 },
		//{ 356, 148 },
		{ 302, 193 },
		{ 424, 194 },
		{ 674, 195 },
		{ 719, 196 }, // Was: 669
		{ 764, 197 },
		{ 782, 198 },
		{ 788, 199 },
		{ 844, 201 }, // Was: 784
		{ 900, 203 },
		{ 903, 204 }, // Was: 900
		{ 906, 205 },
		{ 1014, 206 },
		{ 1100, 207 },
		{ 1144, 208 },
		{ 1264, 209 },
		{ 1304, 210 }, // Was: 1264
		{ 1344, 211 },
		{ 1407, 212 },
		{ 1462, 213 },
		{ 1581, 214 },
		{ 1615, 216 },
		{ 1855, 217 },
		{ 1972, 218 },
		{ 2052, 219 },
		{ 2075, 220 },
		{ 2189, 221 },
		{ 2455, 222 },
		{ 2590, 223 },
		{ 2760, 224 },
		{ 2826, 225 },
		{ 2940, 226 },
		{ 3060, 227 },
		//{ 3066, 228 },
		{ 3167, 229 },
		{ 3172, 230 },
		{ 3300, 231 },
		{ 3415, 232 },
		{ 3450, 233 },
		{ 3750, -1 }
	};
};

class KPL__0_Schedule_3 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(159, 223, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 60060, 61260, 62460 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 16:41:00, interval ~1200s
		//{ -209, 103 },
		//{ -294, 104 },
		{ 138, 106 },
		//{ 446, 107 },
		{ 263, 108 },
		{ 270, 110 },
		{ 310, 111 },
		{ 346, 113 },
		{ 380, 115 }, // Was: 309
		{ 415, 193 },
		{ 541, 194 },
		{ 778, 195 },
		{ 786, 196 },
		{ 871, 197 },
		{ 971, 198 },
		{ 1001, 199 },
		{ 1025, 200 },
		{ 1100, 201 },
		{ 1216, 202 },
		{ 1221, 203 },
		{ 1330, 204 },
		{ 1341, 205 },
		{ 1641, -1 }
	};
};

class MEL__0_Schedule_0 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 96, 128);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 22440, 24900, 25980, 29700, 31200 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 06:14:00, interval ~2460s
		//{ -237, 100 },
		//{ -265, 101 },
		//{ -286, 102 },
		{ -254, 103 },
		{ 120, 106 },
		//{ 139, 107 },
		{ 167, 109 },
		{ 212, 110 },
		{ 262, 112 },
		{ 267, 114 }, // Was: 259
		{ 272, 116 },
		{ 298, 117 },
		{ 391, 118 },
		{ 394, 119 },
		{ 552, 120 },
		{ 572, 121 }, // Was: 418
		{ 592, 122 }, // Was: 424
		{ 612, 123 }, // Was: 503
		{ 635, 124 }, // Was: 548
		{ 659, 125 },
		{ 721, 126 },
		{ 743, 127 },
		{ 792, 128 },
		{ 863, 179 },
		{ 977, 180 },
		{ 1008, 181 },
		{ 1188, -1 }
	};
};

class MEL__1_Schedule_0 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 96, 128);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = {
			23700, 26160, 28560, 29760, 30960, 32460, 34260, 36060, 38340, 41940, 45540, 49140, 
			52740, 56940, 58080, 60300, 61440, 63600, 64800, 67020
		};
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 06:35:00, interval ~2460s
		{ -116, 182 },
		{ 55, 181 },
		{ 196, 180 },
		{ 259, 179 },
		{ 399, 128 },
		{ 492, 127 },
		{ 508, 126 },
		{ 543, 125 },
		{ 660, 124 },
		{ 674, 123 },
		{ 775, 122 },
		{ 789, 121 },
		{ 860, 120 },
		{ 899, 119 },
		{ 929, 118 }, // Was: 896
		{ 960, 117 },
		{ 1025, 116 },
		{ 1030, 114 },
		{ 1074, 112 },
		{ 1099, 110 },
		{ 1120, 109 },
		//{ 1209, 107 },
		{ 1204, 106 },
		//{ 1254, 104 },
		{ 1260, 103 },
		//{ 1350, 102 },
		//{ 1230, 101 },
		{ 1440, -1 }
	};
};

class MEL__0_Schedule_1 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 96, 128);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = {
			27240, 28200, 32280, 34020, 37020, 40620, 44220, 47820, 51420, 55500, 56700, 57780, 
			58740, 59940, 61140, 62280, 63420, 65220
		};
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 07:34:00, interval ~960s
		//{ 23, 100 },
		//{ -287, 101 },
		//{ -294, 102 },
		{ -292, 103 },
		//{ -224, 104 },
		{ 139, 106 },
		//{ 146, 107 },
		{ 184, 109 },
		{ 237, 110 },
		{ 273, 112 },
		{ 285, 114 },
		{ 292, 116 }, // Was: 276
		{ 300, 117 },
		{ 415, 118 },
		{ 416, 119 },
		{ 420, 120 },
		{ 494, 121 },
		{ 530, 122 },
		{ 588, 123 },
		{ 639, 124 },
		{ 723, 125 },
		{ 785, 126 },
		{ 823, 127 },
		{ 867, 128 },
		{ 969, 179 },
		{ 1041, 180 },
		{ 1100, 181 },
		{ 1280, -1 }
	};
};

class MEL__1_Schedule_1 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 96, 128);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 27180, 59100, 62580 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 07:33:00, interval ~31920s
		{ -48, 182 },
		{ 66, 181 },
		{ 273, 180 },
		{ 307, 179 },
		{ 495, 128 },
		{ 503, 127 },
		{ 539, 126 },
		{ 616, 125 },
		{ 659, 124 },
		{ 781, 123 },
		{ 820, 122 }, // Was: 775
		{ 859, 121 },
		{ 895, 120 },
		{ 909, 119 },
		{ 979, 118 },
		{ 986, 117 },
		{ 1095, 114 },
		{ 1125, 112 },
		{ 1145, 110 },
		{ 1152, 109 },
		//{ 1234, 107 },
		{ 1241, 106 },
		//{ 1312, 104 },
		//{ 1471, 102 },
		//{ 1287, 101 },
		{ 1421, -1 }
	};
};

class WRL__1_Schedule_0 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 143, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 20760, 24420 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 05:46:00, interval ~3660s
		{ -5504, 178 },
		{ 199, 177 },
		{ 370, 176 },
		{ 539, 175 },
		{ 1135, 174 },
		{ 1293, 173 },
		{ 1639, 172 },
		{ 1753, 171 },
		{ 2042, 170 },
		{ 2174, 169 },
		{ 2541, 168 },
		{ 2730, 167 },
		{ 3662, 166 },
		{ 3722, 165 },
		{ 3730, 164 },
		{ 4051, 163 },
		{ 4149, 162 },
		{ 4399, 160 },
		{ 4423, 159 },
		{ 4443, 158 }, // Was: 4415
		{ 4500, 157 }, // Was: 4390
		{ 4557, 155 },
		{ 4559, 153 },
		{ 4565, 152 }, // Was: 4508
		{ 4572, 151 },
		{ 4650, 150 },
		{ 4653, 149 },
		{ 4797, 148 },
		{ 4801, 147 },
		{ 4904, 146 }, // Was: 4752
		{ 5007, 145 },
		{ 5027, 144 }, // Was: 4919
		{ 5047, 143 }, // Was: 4887
		{ 5067, 142 }, // Was: 4936
		{ 5087, 141 }, // Was: 5042
		{ 5107, 140 }, // Was: 5052
		{ 5127, 139 }, // Was: 5045
		{ 5137, 138 }, // Was: 5073
		{ 5147, 137 },
		{ 5178, 136 },
		{ 5306, 135 },
		{ 5314, 134 },
		{ 5364, 133 },
		{ 5453, 132 },
		{ 5523, 131 },
		{ 5532, 130 },
		{ 5561, 129 },
		{ 5653, 128 },
		{ 5660, 127 },
		{ 5672, 126 },
		{ 5768, 125 },
		{ 5882, 124 },
		{ 6127, 123 },
		{ 6147, 122 }, // Was: 5944
		{ 6167, 121 }, // Was: 6022
		{ 6187, 120 }, // Was: 6030
		{ 6207, 119 }, // Was: 6132
		{ 6227, 118 }, // Was: 6064
		{ 6247, 117 }, // Was: 6178
		{ 6267, 116 }, // Was: 6063
		{ 6287, 114 }, // Was: 6114
		{ 6307, 112 }, // Was: 6243
		{ 6327, 110 }, // Was: 6242
		{ 6365, 109 }, // Was: 6260
		{ 6403, 107 },
		//{ 6350, 106 },
		{ 6434, 104 },
		{ 6734, -1 }
	};
};

class WRL__1_Schedule_1 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 143, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 22800 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 06:20:00
		{ -6331, 178 },
		{ 132, 177 },
		{ 322, 176 },
		{ 439, 175 },
		{ 1077, 174 },
		{ 1332, 173 },
		{ 1552, 172 },
		{ 1644, 171 },
		{ 2047, 170 },
		{ 2164, 169 },
		{ 2604, 168 },
		{ 2759, 167 },
		{ 3724, 164 },
		{ 4079, 163 },
		{ 4203, 162 },
		{ 4443, 160 },
		{ 4642, 159 },
		{ 4662, 158 }, // Was: 4525
		{ 4682, 157 }, // Was: 4561
		{ 4702, 156 }, // Was: 4569
		{ 4725, 155 }, // Was: 4565
		{ 4748, 153 },
		{ 4775, 151 }, // Was: 4679
		{ 4803, 150 },
		{ 4811, 149 },
		{ 4867, 148 }, // Was: 4797
		{ 4923, 146 },
		{ 4968, 145 },
		{ 5007, 144 },
		{ 5123, 142 },
		{ 5272, 141 },
		{ 5274, 140 }, // Was: 5260
		{ 5276, 139 },
		{ 5329, 138 }, // Was: 5266
		{ 5383, 137 },
		{ 5477, 136 },
		{ 5598, 135 },
		{ 5717, 134 },
		{ 5735, 133 },
		{ 5806, 132 }, // Was: 5634
		{ 5878, 130 },
		{ 5921, 129 },
		{ 5963, 128 },
		{ 6087, 127 },
		{ 6090, 126 }, // Was: 6013
		{ 6093, 125 },
		{ 6300, 124 },
		{ 6331, 123 }, // Was: 6130
		{ 6363, 121 },
		{ 6483, 117 },
		{ 6714, 112 },
		{ 6727, 110 },
		{ 6747, 109 }, // Was: 6484
		{ 6753, 107 }, // Was: 6683
		//{ 6760, 106 },
		{ 6922, 104 },
		//{ 6680, 103 },
		{ 7222, -1 }
	};
};

class WRL__0_Schedule_0 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 143, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 30060, 45900 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 08:21:00, interval ~15840s
		//{ 144, 103 },
		{ -2112, 104 },
		//{ 167, 106 },
		{ 265, 109 },
		{ 300, 110 },
		{ 379, 112 },
		{ 396, 114 },
		{ 402, 116 },
		{ 411, 117 },
		{ 415, 118 },
		{ 543, 119 },
		{ 547, 121 },
		{ 552, 122 },
		{ 621, 123 },
		{ 650, 124 },
		{ 777, 125 },
		{ 782, 126 },
		{ 892, 127 },
		{ 1007, 128 },
		{ 1071, 129 },
		{ 1117, 130 },
		{ 1174, 131 },
		{ 1197, 132 }, // Was: 1144
		{ 1220, 133 },
		{ 1230, 134 },
		{ 1358, 135 },
		{ 1364, 136 },
		{ 1467, 137 },
		{ 1481, 138 },
		{ 1577, 139 },
		{ 1679, 140 },
		{ 1699, 141 }, // Was: 1497
		{ 1781, 142 }, // Was: 1610
		{ 1863, 143 },
		{ 1883, 144 }, // Was: 1737
		{ 1903, 145 }, // Was: 1717
		{ 1923, 146 }, // Was: 1740
		{ 1943, 148 }, // Was: 1804
		{ 1963, 149 }, // Was: 1860
		{ 1983, 150 }, // Was: 1870
		{ 2003, 151 }, // Was: 1915
		{ 2053, 152 }, // Was: 1980
		{ 2103, 153 },
		{ 2123, 154 }, // Was: 2038
		{ 2136, 155 }, // Was: 2100
		{ 2150, 156 },
		{ 2190, 157 },
		{ 2337, 158 },
		{ 2348, 160 },
		//{ -2804, 161 },
		{ 2549, 162 }, // Was: 2230
		{ 2751, 163 },
		{ 2981, 164 },
		{ 3142, 165 },
		{ 3396, 166 }, // Was: 3105
		{ 3650, 167 },
		{ 4010, 168 },
		{ 4260, 169 },
		{ 4700, 170 },
		{ 4821, 171 },
		{ 5181, 172 },
		{ 5261, 173 },
		{ 5581, 174 },
		{ 5785, 175 },
		{ 6441, 176 },
		{ 6561, 177 },
		{ 7103, 178 },
		{ 7403, -1 }
	};
};

class WRL__1_Schedule_2 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 143, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 37800, 56280 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 10:30:00, interval ~18480s
		{ -1700, 178 },
		{ 192, 177 },
		{ 348, 176 },
		{ 564, 175 },
		{ 1288, 174 },
		{ 1422, 173 },
		{ 1744, 172 },
		{ 1803, 171 },
		{ 2110, 170 },
		{ 2240, 169 },
		{ 2613, 168 },
		{ 2843, 167 },
		{ 3770, 166 },
		{ 3790, 165 },
		{ 3838, 164 },
		{ 3968, 163 },
		{ 4158, 162 },
		//{ 7104, 161 },
		{ 4319, 160 },
		{ 4435, 159 },
		{ 4498, 158 }, // Was: 4330
		{ 4561, 157 },
		{ 4563, 155 }, // Was: 4440
		{ 4565, 154 },
		{ 4597, 153 }, // Was: 4560
		{ 4630, 152 },
		{ 4652, 151 }, // Was: 4560
		{ 4675, 150 },
		{ 4915, 149 },
		{ 4935, 148 }, // Was: 4742
		{ 4955, 147 }, // Was: 4799
		{ 4975, 146 }, // Was: 4760
		{ 4995, 145 }, // Was: 4902
		{ 5015, 144 }, // Was: 4867
		{ 5035, 143 }, // Was: 4858
		{ 5055, 142 }, // Was: 4940
		{ 5075, 140 }, // Was: 5035
		{ 5095, 139 }, // Was: 4917
		{ 5112, 137 }, // Was: 5040
		{ 5130, 136 },
		{ 5240, 135 },
		{ 5250, 134 },
		{ 5360, 133 },
		{ 5449, 132 },
		{ 5487, 131 }, // Was: 5399
		{ 5525, 130 },
		{ 5545, 129 }, // Was: 5441
		{ 5572, 128 }, // Was: 5519
		{ 5600, 127 },
		{ 5677, 126 },
		{ 5737, 125 },
		{ 5875, 124 },
		{ 5877, 123 }, // Was: 5836
		{ 5879, 122 },
		{ 5956, 121 },
		{ 5989, 120 },
		{ 6110, 119 },
		{ 6117, 118 }, // Was: 6003
		{ 6125, 117 },
		{ 6351, 116 },
		{ 6371, 114 }, // Was: 6238
		{ 6526, 112 }, // Was: 6235
		{ 6681, 110 },
		{ 6701, 109 }, // Was: 6325
		{ 6721, 107 }, // Was: 6330
		//{ 6297, 106 },
		{ 6741, 104 }, // Was: 6395
		{ 6981, -1 }
	};
};

class WRL__0_Schedule_3 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 143, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 65880 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 18:18:00
		{ -2264, 104 },
		//{ 160, 106 },
		{ 100, 107 },
		{ 270, 109 },
		{ 335, 112 },
		{ 452, 114 },
		{ 472, 116 }, // Was: 400
		{ 492, 117 }, // Was: 387
		{ 512, 118 }, // Was: 455
		{ 532, 119 }, // Was: 465
		{ 556, 121 }, // Was: 485
		{ 580, 122 },
		{ 600, 123 },
		{ 695, 124 },
		{ 722, 125 },
		{ 854, 127 },
		{ 997, 128 },
		{ 1050, 129 },
		{ 1202, 130 },
		{ 1222, 131 }, // Was: 1122
		{ 1311, 132 }, // Was: 1180
		{ 1401, 133 },
		{ 1410, 135 }, // Was: 1313
		{ 1420, 136 },
		{ 1540, 137 },
		{ 1605, 139 }, // Was: 1472
		{ 1670, 140 },
		{ 1843, 142 },
		{ 1884, 143 }, // Was: 1778
		{ 1925, 144 },
		{ 1960, 145 },
		{ 2055, 146 }, // Was: 1898
		{ 2151, 147 },
		{ 2171, 148 }, // Was: 2044
		{ 2191, 150 }, // Was: 2097
		{ 2204, 151 }, // Was: 2107
		{ 2217, 153 },
		{ 2257, 154 }, // Was: 2170
		{ 2297, 155 },
		{ 2317, 156 }, // Was: 2203
		{ 2337, 157 }, // Was: 2136
		{ 2368, 158 }, // Was: 2155
		{ 2400, 159 },
		{ 2525, 160 },
		{ 2542, 162 },
		{ 2682, 163 },
		{ 2947, 164 },
		{ 3052, 165 },
		{ 3137, 166 },
		{ 3764, 167 },
		{ 4097, 168 },
		{ 4362, 169 },
		{ 4762, 170 },
		{ 4882, 171 },
		{ 5202, 172 },
		{ 5272, 173 },
		{ 5612, 174 },
		{ 5717, 175 },
		{ 6333, 176 },
		{ 6482, 177 },
		{ 6550, 178 },
		{ 6850, -1 }
	};
};

class WRL__0_Schedule_2 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 143, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 63000 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 17:30:00
		//{ -1024, 103 },
		//{ 119, 106 },
		{ 89, 107 },
		{ 227, 109 },
		{ 1163, 110 },
		{ 1183, 112 }, // Was: 326
		{ 1203, 116 }, // Was: 333
		{ 1682, 117 }, // Was: 353
		{ 2161, 118 },
		{ 2181, 119 }, // Was: 1328
		{ 2201, 121 }, // Was: 486
		{ 2221, 122 }, // Was: 490
		{ 2241, 123 }, // Was: 582
		{ 2261, 124 }, // Was: 640
		{ 2281, 125 }, // Was: 718
		{ 2301, 127 }, // Was: 832
		{ 2321, 128 }, // Was: 915
		{ 2536, 129 }, // Was: 962
		{ 2751, 130 },
		{ 2771, 131 }, // Was: 1039
		{ 2791, 132 }, // Was: 1117
		{ 2811, 133 }, // Was: 1988
		{ 2831, 135 }, // Was: 1310
		{ 2851, 136 }, // Was: 1302
		{ 2871, 137 }, // Was: 1457
		{ 2891, 138 }, // Was: 1477
		{ 2911, 139 }, // Was: 1487
		{ 3076, 140 }, // Was: 1497
		{ 3241, 141 },
		{ 3261, 142 }, // Was: 1555
		{ 3281, 144 }, // Was: 1623
		{ 3301, 145 }, // Was: 2458
		{ 3321, 146 }, // Was: 1732
		{ 3341, 148 }, // Was: 1742
		{ 3361, 150 }, // Was: 1921
		{ 3381, 151 }, // Was: 2698
		{ 3401, 153 }, // Was: 1973
		{ 3621, 155 }, // Was: 2063
		{ 3842, 156 },
		{ 3862, 157 }, // Was: 2117
		{ 3916, 158 }, // Was: 2165
		{ 3971, 160 },
		{ 3991, 162 }, // Was: 2338
		{ 4011, 163 }, // Was: 2523
		{ 4031, 164 }, // Was: 2697
		{ 4051, 165 }, // Was: 2823
		{ 4071, 166 }, // Was: 2928
		{ 4091, 167 }, // Was: 3503
		{ 4117, 168 }, // Was: 3882
		{ 4143, 169 },
		{ 4602, 170 },
		{ 4757, 171 },
		{ 5032, 172 },
		{ 5123, 173 },
		{ 5442, 174 },
		{ 5623, 175 },
		{ 6187, 176 },
		{ 6402, 177 },
		{ 6567, 178 },
		{ 6867, -1 }
	};
};

class WRL__0_Schedule_1 : public TrainRoute {
  public:
	const std::vector<TimetableEntry>& getEntries() const override {
		return timetable;
	}

	CRGB getColor() const override {
		return CRGB(255, 143, 0);
	}

	const std::vector<uint32_t>& getStartTimes() const override {
		static const std::vector<uint32_t> startTimes = { 59100 };
		return startTimes;
	}

  private:
	static const inline std::vector<TimetableEntry> timetable = {  // First departure: 16:25:00
		{ 1341, 104 },
		//{ 1221, 106 },
		{ 1821, 107 }, // Was: 1101
		{ 2301, 109 },
		{ 2321, 112 },
		{ 2421, 117 },
		{ 2581, 122 },
		{ 2661, 123 },
		{ 2681, 124 },
		{ 2811, 125 },
		{ 2901, 128 },
		{ 3031, 129 },
		{ 3181, 132 },
		{ 3302, 136 },
		{ 3501, 138 },
		{ 3511, 139 },
		{ 3521, 140 },
		{ 3661, 144 },
		{ 3791, 148 },
		{ 3901, 151 },
		{ 4021, 153 },
		{ 4031, 154 },
		{ 4101, 155 },
		{ 4151, 156 },
		{ 4262, 159 },
		{ 4271, 160 },
		{ 4348, 162 },
		{ 4481, 163 },
		{ 4741, 164 },
		{ 4833, 165 },
		{ 4951, 166 },
		{ 5461, 167 },
		{ 5891, 168 },
		{ 6071, 169 },
		{ 6521, 170 },
		{ 6681, 171 },
		{ 6981, 172 },
		{ 7101, 173 },
		{ 7391, 174 },
		{ 7631, 175 },
		{ 8231, 176 },
		{ 8421, 177 },
		{ 8721, -1 }
	};
};

// === Global List of Routes ===
inline const std::vector<const TrainRoute*> getAllRoutes() {
	static const std::vector<const TrainRoute*> routes = {
		new JVL__0_Schedule_0(),
		new JVL__1_Schedule_0(),
		new JVL__0_Schedule_1(),
		new JVL__0_Schedule_2(),
		new JVL__1_Schedule_1(),
		new HVL__0_Schedule_0(),
		new HVL__1_Schedule_0(),
		new HVL__1_Schedule_1(),
		new HVL__1_Schedule_2(),
		new HVL__1_Schedule_3(),
		new HVL__0_Schedule_1(),
		new HVL__0_Schedule_2(),
		new HVL__1_Schedule_4(),
		new HVL__1_Schedule_5(),
		new KPL__0_Schedule_0(),
		new KPL__1_Schedule_0(),
		new KPL__1_Schedule_1(),
		new KPL__1_Schedule_2(),
		new KPL__0_Schedule_1(),
		new KPL__1_Schedule_3(),
		new KPL__1_Schedule_4(),
		new KPL__1_Schedule_5(),
		new KPL__0_Schedule_2(),
		new KPL__0_Schedule_3(),
		new MEL__0_Schedule_0(),
		new MEL__1_Schedule_0(),
		new MEL__0_Schedule_1(),
		new MEL__1_Schedule_1(),
		new WRL__1_Schedule_0(),
		new WRL__1_Schedule_1(),
		new WRL__0_Schedule_0(),
		new WRL__1_Schedule_2(),
		new WRL__0_Schedule_3(),
		new WRL__0_Schedule_2(),
		new WRL__0_Schedule_1(),
	};
	return routes;
}

