#!/usr/bin/env python3
"""Generate gzip-compressed PROGMEM assets from the Svelte device console."""

from __future__ import annotations

import gzip
import hashlib
import json
import mimetypes
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DIST_DIRECTORY = PROJECT_ROOT / "Device Web" / "dist"
OUTPUT_HEADER = PROJECT_ROOT / "include" / "deviceWebAssets.h"

CONTENT_TYPES = {
    ".css": "text/css; charset=utf-8",
    ".html": "text/html; charset=utf-8",
    ".ico": "image/x-icon",
    ".js": "text/javascript; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".png": "image/png",
    ".svg": "image/svg+xml",
    ".txt": "text/plain; charset=utf-8",
}


def content_type_for(path: Path) -> str:
    """Return a browser-safe content type for a generated asset."""
    return CONTENT_TYPES.get(
        path.suffix.lower(),
        mimetypes.guess_type(path.name)[0] or "application/octet-stream",
    )


def variable_name_for(path: Path) -> str:
    """Return a C++ identifier for an asset path."""
    return "device_web_" + "".join(
        character if character.isalnum() else "_" for character in path.as_posix()
    )


def url_path_for(path: Path) -> str:
    """Map Vite's root document to the device root and preserve asset paths."""
    return "/" if path.as_posix() == "index.html" else "/" + path.as_posix()


def format_bytes(data: bytes) -> str:
    """Format binary data into compact C++ array lines."""
    lines: list[str] = []
    for offset in range(0, len(data), 16):
        values = ", ".join(f"0x{value:02x}" for value in data[offset : offset + 16])
        lines.append(f"    {values},")
    return "\n".join(lines)


def source_digest() -> str:
    """Return a stable digest for source files that affect generated assets."""
    digest = hashlib.sha256()
    for path in sorted(
        path for path in (PROJECT_ROOT / "Device Web").rglob("*") if path.is_file()
    ):
        relative_path = path.relative_to(PROJECT_ROOT / "Device Web")
        if relative_path.parts[0] in {"dist", "node_modules"}:
            continue
        digest.update(relative_path.as_posix().encode("utf-8"))
        digest.update(path.read_bytes())
    digest.update(Path(__file__).read_bytes())
    return digest.hexdigest()


def assets_are_current() -> bool:
    """Check whether the generated header matches the current web source."""
    if not OUTPUT_HEADER.is_file():
        return False
    first_line = OUTPUT_HEADER.read_text(encoding="ascii").splitlines()[0]
    return first_line == f"// Source digest: {source_digest()}"


def generate() -> None:
    """Write the generated device asset header from the Vite build output."""
    if not DIST_DIRECTORY.is_dir():
        raise FileNotFoundError(f"Device web build output not found: {DIST_DIRECTORY}")

    assets = sorted(path for path in DIST_DIRECTORY.rglob("*") if path.is_file())
    if not assets:
        raise RuntimeError(f"No device web assets found in {DIST_DIRECTORY}")

    declarations: list[str] = []
    entries: list[str] = []
    for asset in assets:
        relative_path = asset.relative_to(DIST_DIRECTORY)
        variable_name = variable_name_for(relative_path)
        compressed_data = gzip.compress(asset.read_bytes(), compresslevel=9, mtime=0)
        declarations.append(
            f"const uint8_t {variable_name}[] PROGMEM = {{\n{format_bytes(compressed_data)}\n}};"
        )
        entries.append(
            "    {"
            f"{json.dumps(url_path_for(relative_path))}, "
            f"{json.dumps(content_type_for(relative_path))}, "
            f"{variable_name}, sizeof({variable_name})"
            "},"
        )

    header = f"// Source digest: {source_digest()}\n"
    header += """// Generated by tools/generate_device_web_assets.py. Do not edit manually.
#pragma once

#include <Arduino.h>

struct DeviceWebAsset {
    const char* path;
    const char* contentType;
    const uint8_t* data;
    size_t size;
};

namespace deviceWebAssets {
"""
    header += "\n\n".join(declarations)
    header += "\n\nconst DeviceWebAsset assets[] = {\n"
    header += "\n".join(entries)
    header += "\n};\n"
    header += "constexpr size_t assetCount = sizeof(assets) / sizeof(assets[0]);\n"
    header += "}  // namespace deviceWebAssets\n"

    OUTPUT_HEADER.write_text(header, encoding="ascii", newline="\n")
    total_size = sum(asset.stat().st_size for asset in assets)
    compressed_size = sum(
        len(gzip.compress(asset.read_bytes(), compresslevel=9, mtime=0))
        for asset in assets
    )
    print(
        f"Generated {OUTPUT_HEADER.relative_to(PROJECT_ROOT)} from {len(assets)} assets ({total_size} bytes -> {compressed_size} bytes gzip)."
    )


if __name__ == "__main__":
    generate()
