name: Deploy Web Installer to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v6
        with:
          cache: 'pip' # caching pip dependencies
          python-version: "3.14"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio intelhex
        # Intel hex needed for bug: https://github.com/platformio/platform-espressif32/issues/1632

      - name: Build and prepare installer
        run: python .github/scripts/build_installer.py

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "_site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
